
#ifndef __BCGEN_H__
#define __BCGEN_H__

#include "bcgen/context.h"
#include "bcgen/funcman.h"
#include "bcgen/instr.h"
#include "bcgen/return.h"
#include "bcgen/tmpvar.h"
#include "general/funcdef.h"
#include "general/types.h"
#include <string>
#include <vector>

class Compiler;
class Parser;

/**
 * Instructions are stored in functions which can then call each other
 */
struct BCFunc {
    BCFunc(std::string name);
    std::string name;
    std::vector<BCInstr> instrList;
};

/**
 * Manager object to keep track of stuff while generating bytecode, which is
 * done by the parse node objects. This object also stores the generated
 * bytecode
 */
class BCManager {

public:

    /**
     * Constructor
     * @param comp The compiler component
     */
    BCManager(Compiler *comp);

    /**
     * Destructor
     */
    ~BCManager();

    /**
     * Generate bytecode
     * @note This function assumes that the parser generated a parse tree, which
     * is used in this function
     * @post Generated bytecode is stored in `funcList`
     */
    void generate();

    /**
     * Get all of the generated bytecode
     * @return A pointer to a vector containing the functions which contain
     * bytecode instructions
     */
    const std::vector<BCFunc *> *getBytecode() const;

    /**
     * Get a pointer to the function that is currently being written to
     * @return A pointer to the top function on the `funcStack`
     */
    BCFunc *curFunc() const;

    /**
     * Write an instruction to the current function
     * @param instr The instruction to be appended
     * @post An instruction is appended to the top function of the `funcStack`
     */
    void write(BCInstr instr);

    /**
     * Create a new function and add it to the function stack
     * @param name The name of the function (optional)
     * @note If no name is given, a unique number will be assigned
     */
    void addFunc(std::string name = "");

    /**
     * Remove the top function from the function stack
     * @post The top element of the `funcStack` is removed, if there is any
     * @note The function will still be present in the `funcList`
     */
    void popFunc();

    /**
     * Get a pointer to the top function on the function stack
     * @return Top element of `funcStack`
     */
    BCFunc *topFunc() const;

    /**
     * Set the contents of the function stack
     * @param stack A vector of pointer to BCFuncs representing the function
     * stack
     * @post `funcStack` is set to the value of `stack`
     */
    void setFuncStack(std::vector<BCFunc *> stack);

    // Context stack
    ContextStack ctx;

    // Function manager
    FuncManager funcs;

    // Temporary variable manager
    TmpVarManager tmp;

    // The compiler component
    Compiler *comp;

    // Current return type and value
    Return ret;

private:

    // List of functions that are generated
    std::vector<BCFunc *> funcList;

    // Function stack, which helps with adding instructions to the right
    // functions
    std::vector<BCFunc *> funcStack;

    // Counter to keep track of unique IDs/names assigned to functions
    unsigned int uniqueFuncId;

};

#endif