
#ifndef __PARSENODE_FUNC_H__
#define __PARSENODE_FUNC_H__

#include "bcgen/context.h"
#include "general/loc.h"
#include "general/types.h"
#include "general/var.h"
#include "parsenodes/parsenode.h"
#include <string>
#include <vector>

class BCFunc;
class BCManager;
class CodeBlockNode;

/**
 * Function generation table entry
 */
struct FuncGenEntry {
    bool hasGenerated;
    BCFunc *bcfunc;
    std::vector<std::string> constValues;
};

class FuncNode : public ParseNode {

public:

    /**
     * Constructor
     * @param retType THe return type of the function
     * @param name Name of the function
     * @param params The parameters of the function
     * @param codeblock Code inside the function
     * @param loc The location of the parse node
     */
    FuncNode(Type retType, std::string name, std::vector<Param> params,
    CodeBlockNode *codeblock, Loc loc);

    /**
     * Destructor
     */
    virtual ~FuncNode() override;

    /**
     * Get the children of this parse node
     * @return A vector with pointers to the child nodes
     */
    virtual std::vector<ParseNode *> children() const override;

    /**
     * Generate bytecode for this parse node
     * @param man The main bytecode manager
     */
    virtual void bytecode(BCManager &man) override;

    /**
     * Generate the bytecode for this function, with the given constants filled
     * in
     * @param man The main bytecode manager
     * @param constValues The values of the constant arguments
     * @return The name of the function to call
     * @post Stores the name of the generated bytecode function given the
     * constant values in `aliases`
     * @note If the bytecode for this set of constants was already generated, no
     * new bytecode will be generated
     */
    std::string bytecode(BCManager &man, std::vector<std::string> constValues);

    /**
     * Get the return type of the function
     * @return The return type
     */
    Type getReturnType() const;

    /**
     * Get the name of the function
     * @return The name of the function
     */
    std::string getName() const;

    /**
     * The the parameter types of this function
     * @return A vector containing the parameter types
     */
    std::vector<Type> getParamTypes() const;

    /**
     * Check if this function accepts the given parameter types
     * @param types A vector of types to check for
     * @return Boolean indicating if the function accepts the given types
     */
    bool acceptTypes(std::vector<Type> types) const;

    /**
     * Check if this function still has entries in its generation table that
     * need to be generated
     * @return A boolean indicating if there as entries in `genTable` with
     * `hasGenerated` false
     */
    bool hasUngeneratedEntries() const;

    /**
     * Generate entries in the generation table that have not been generated yet
     * @param man The main bytecode manager
     * @post All entries that were previously in `genTable` have `hasGenerated`
     * set to true
     */
    void generateEntries(BCManager &man);

    /**
     * Add an entry to the generation table
     * @param man The main bytecode manager
     * @param constValues The constant values to be generated with this entry
     * @return The callname that is associated with this entry
     */
    std::string addGenerationEntry(BCManager &man, std::vector<std::string>
    constValues);

    /**
     * Check for name conflicts and throw an error if there is one
     * @param man The main bytecode manager
     */
    void checkNameConflicts(BCManager &man) const;

    /**
     * Get a list of default constant values, based on the function
     * @return A vector of strings containing "default" constant values for the
     * function based on its parameter types, for example with parameters (int,
     * const int, const str) the default constants would be ("0", "")
     */
    std::vector<std::string> defaultConstValues() const;

private:

    /**
     * Check if the function has already been defined with the same parameter
     * types (ignoring const)
     * @param man The main bytecode manager
     * @return Boolean indicating if another function was found
     */
    bool hasNameConflict(BCManager &man) const;

    /**
     * Check if the function has a name conflict with the given other function
     * @return Boolean indicating if there is a conflict
     */
    bool hasNameConflict(FuncNode *other) const;

    /**
     * Initialize global variables by adding 0 to them
     * @param man The global bytecode manager
     */
    void initGlobalVars(BCManager &man);

    /**
     * Initialize parameters by copying them to their correct variables
     * @param man The global bytecode manager
     * @param constValues The constant values to initialize
     */
    void initParams(BCManager &man, std::vector<std::string> constValues);

    /**
     * Find a generation table entry based on the constant values input
     * @param constValues The constant values to compare with
     * @return A pointer to the generation table entry, or null if none is found
     */
    FuncGenEntry *getGenerationEntry(std::vector<std::string> constValues);

    // Return type of the function
    Type retType;

    // Name of the function
    std::string name;

    // Function parameters
    std::vector<Param> params;

    // Content of the function
    CodeBlockNode *codeblock;

    // Generation table: keeps track of which functions given constant input
    // still have to be generated and already have been generated
    std::vector<FuncGenEntry> genTable;

};

#endif